# Generated by Django 5.0.7 on 2024-08-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_task_due_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="status",
            new_name="completed",
        ),
    ]
